name: main

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_IMAGE: chuhlomin/teams

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Test
        run: go test -cover ./...

      - name: Build and push to CR
        if: github.event_name == 'push'
        uses: chuhlomin/actions/docker-build-push@main
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest
